name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main                  # add other branches if you push to them
      - merge-full-ui-and-apis
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build API (Node Azure Functions)
      - name: Install API deps
        working-directory: api
        run: npm ci

      # Build frontend (optional—kept safe if no package.json)
      - name: Build Frontend
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"   # your index.html lives here
          api_location: "api"        # your Functions live here
          output_location: ""        # set to "dist" if your build outputs to /frontend/dist
