name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]        # <-- change to your default branch if not 'main'
  workflow_dispatch:          # allows manual runs from the Actions tab

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: build frontend if you have a package.json inside /frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi

      # Install API deps (Functions)
      - name: Setup Functions
        working-directory: api
        run: npm ci

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: ""
