name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # -------- FRONTEND (optional build) --------
      - name: Install frontend deps
        working-directory: frontend
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
          else
            echo "No frontend/package.json. Skipping install."
          fi

      - name: Build frontend
        working-directory: frontend
        run: |
          if [ -f package.json ] && npm run | grep -q " build"; then
            npm run build
          else
            echo "No frontend build script. Skipping."
          fi

      # -------- API (Azure Functions) --------
      - name: Install API deps
        working-directory: api
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci --omit=dev
            else
              npm install --omit=dev --no-audit --no-fund
            fi
          else
            echo "No api/package.json. Skipping install."
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: ""
