name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug paths
        run: |
          echo "== root ==" && ls -la
          echo "== frontend ==" && ls -la frontend || true
          echo "== api ==" && ls -la api || true
          echo "== api subfolders ==" && find api -maxdepth 2 -type d -print

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: ""
